services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3500:3000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - DATABASE_URL=file:/app/data/dev.db
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      - ./.cache:/app/.cache
    restart: always
